### ISSUE TITLE
Add "Smooth Scroll" animation type to Chat Bubbles widget

### ISSUE THREAD

**Issue by jGreenBytes** [zaytri/stream-elements-widgets#3]
One feature I noticed in a vtuber's was a chat that scrolls smoothly. 

I understand this is a feature that is not normally seen in twitch chat nor any 3rd party software solution. It seems any time a new message comes up, the previous message instantaneously jumps to make space for that message. 

This new feature would allow the option to have an animation type that instead adds the new message out of sight and then smoothly "scrolls" that message, along with all previous messages, into the main view. As the older messages leave the main view, they would be deleted. 

The most similar animation type to this would be "Dynamic" though even this animation type has a noticable jagged jump before smoothly "opening" the message.

**Comment by zaytri** [comment]
hmmm
that'd still be jarring in an active chat, if chat messages are being sent faster than the scroll animation

messages could be queued to fix that, but then messages wouldn't necessarily be live synced

tiktok's solution for that seems to be to have a queue and then send everything in the queue at once; so if there's 3 messages in the queue during the previous message's scroll animation, scroll all 3 new messages in simultaneously in 1 animation

this would also involve calculating bubble size on demand (which is already done for the random positioning), factoring in the space between bubbles, and making the new queue system

it's definitely not trivial to get this working, could be nice to have at some point (maybe for v3) but it's not something I'm planning on adding soon outside of custom commissions
