### ISSUE TITLE
Resizing is not working in 2-3 key ways

### ISSUE THREAD

**Issue by AfterglowAmpharos** [zaytri/stream-elements-widgets#4]
For reasons I don't understand, resizing doesn't work correctly.

1. If I type custom numbers into the Width and Height text fields, the chat bubbles spawn outside the specified boundaries.
Let's assume a starting width and height of 600 and 900.
example 1: I type 800 into the Height box, hit enter, save, and send a test message. The new bubble spawns outside the boundary, so it gets cut off at the bottom, I can only see the top half.
example 2: I type 1000 into the Height box, hit enter, save, and send a test message. The new bubble spawns 100px above the specified bottom border, instead of right at the bottom.
(this error does not occur when resizing with dragging the edges, only with making inputs to the numbered text fields)

2. If I drag one of the edges of the blue rectangle, not only does the width change, the height does too. 
Let's assume a starting width and height of 600 and 900.
example 1: I drag the left edge slightly to the left, and this results in 612 width and 904 height.
example 2: I drag the left edge slightly to the right, and this results in 591 width and 904 height.
example 3: I drag the top edge slightly up, and this results in 604 width and 908 height.
example 4: I drag the top edge slightly down, and this results in 604 width and 891 height.
As you can see, the height always slightly increases when I make adjustments to the width, and vice versa, when the expected behaviour is for the edge I didn't touch would stay the same.

3. When dragging the borders to resize, this results in fractions of pixels as the final size, e.g. 670.53px x 858.84px. This could become a hassle for streamers trying to get things exactly aligned to the dimensions of their monitor or their game window.

**Comment by zaytri** [comment]
These are bugs with the StreamElements editor itself.
1. Typing in specific numbers works, you just need to save and then refresh for it to update properly.
2. SE Editor bug.
3. SE Editor... feature? Not a good one.

**Comment by AfterglowAmpharos** [comment]
Thanks, your reply about issue 1 helps!
